import { Link } from 'react-router-dom';
import LogoMark from './LogoMark';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-slate-950 font-sans text-white">
      <header className="border-b border-indigo-500/20 bg-[rgba(6,4,18,0.76)] backdrop-blur-2xl">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-3 text-white/95 no-underline">
            <LogoMark size={36} />
            <span className="font-semibold tracking-widest text-base">ListMate</span>
          </Link>
          <Link to="/" className="text-sm text-white/50 hover:text-indigo-300 transition">← Back to home</Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-20 lg:px-8">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: 23 July 2026</p>

        <div className="space-y-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. About ListMate</h2>
            <p className="mb-3">ListMate is a trading name of <strong className="text-white">lookntook ltd</strong> ("we", "us", "our"), a company registered in England &amp; Wales under company number 14851224, with its registered office at 85 Blackburn Way, Hounslow, England, TW4 5AH.</p>
            <p>ListMate is an AI-powered listing generation service for UK marketplace resellers. By accessing or using ListMate at listmate.co.uk (the "Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Eligibility</h2>
            <p>You must be at least 18 years old and reside in the United Kingdom to use ListMate. By using the Service you confirm that you meet these requirements. Business accounts are permitted.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Your Account</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at support@listmate.co.uk if you suspect unauthorised access. We reserve the right to terminate accounts that violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="space-y-2 list-disc pl-5">
              <li>Use the Service to generate fraudulent, misleading, or illegal listings.</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service.</li>
              <li>Share your account credentials with other people.</li>
              <li>Use automated scripts or bots to interact with the Service.</li>
              <li>Resell or sublicense access to the Service without our written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Plans, Billing & Cancellation</h2>
            <p className="mb-3">ListMate offers a Free plan (5 listings/month) and paid plans (Starter at £5.99/mo, Pro at £11.99/mo). Paid plans are billed monthly via Stripe. Prices are inclusive of any applicable VAT.</p>
            <p className="mb-3">You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period — you retain access to paid features until then. We do not provide refunds for partial months.</p>
            <p>We reserve the right to change pricing with 30 days' notice to your registered email address.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. AI-Generated Content</h2>
            <p>Listings generated by ListMate are produced by an AI model. You are responsible for reviewing AI-generated content before publishing it on any marketplace. We make no warranty that generated listings are accurate, complete, or compliant with any platform's policies. You own the output of listings you generate.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>The ListMate platform, brand, and underlying technology are owned by us. You retain ownership of any content you submit (item descriptions, images, etc.). You grant us a limited licence to process that content solely to provide the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by UK law, ListMate shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Service. Our total liability to you in any month shall not exceed the amount you paid us in that month.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Service Availability</h2>
            <p className="mb-3">We aim for high availability but do not guarantee uninterrupted access to the Service. We may suspend the Service temporarily for maintenance, updates, or circumstances beyond our control.</p>
            <p>If we decide to permanently discontinue the Service, we will give you at least 30 days' notice by email, provide a window in which you can export your listing history, and refund any prepaid amounts covering the period after the shutdown date. See our Privacy Policy for how your data is handled on shutdown.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Governing Law</h2>
            <p>These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. Material changes will be communicated via email or a prominent notice on the Service at least 14 days before they take effect. Continued use of the Service after that date constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Contact</h2>
            <p>For any questions about these Terms, contact us at <a href="mailto:support@listmate.co.uk" className="text-indigo-300 hover:text-white transition">support@listmate.co.uk</a>.</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-indigo-500/20 px-6 py-8 text-center text-xs text-white/30">
        <p>© 2026 ListMate · lookntook ltd (Company No. 14851224) · <Link to="/terms" className="hover:text-indigo-300 transition">Terms</Link> · <Link to="/privacy" className="hover:text-indigo-300 transition">Privacy</Link> · <Link to="/refund" className="hover:text-indigo-300 transition">Refunds</Link> · <Link to="/contact" className="hover:text-indigo-300 transition">Contact</Link></p>
      </footer>
    </div>
  );
}
